### ISSUE TITLE
Feature request: Option to disable info popup

### ISSUE THREAD

**Issue by DimkaDim** [sblask-webextensions/webextension-enhanced-image-viewer#4]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

It is necessary to have an option to disable info popup when changing scaling mode.

In my case, I only use two modes: Natural size and Fit image to browser window (respecting the aspect ratio), and it is obvious which one is selected, info popup only distracts and irritates.

For the time being, I've done this for myself by deleting 2 lines in function flashInfo():
showInfo();
infoTimeout = setTimeout(hideInfo, 2000);

**Comment by sblask** [comment]
I will probably make the time configurable. So 0 for off and then whatever value is provided as argument to setTimeout. But I don't have much time on my hands at the moment...
