### ISSUE TITLE
suggestion: default mode

### ISSUE THREAD

**Issue by rezad1393** [sblask-webextensions/webextension-enhanced-image-viewer#54]
may I suggest that a default mode be added that can be selected from all modes?

right now user has two options:
remember last mode
dont remember last mode

the first option is useful.

but the second one make the first selected mode the default mode and because they are hardcoded in addon then I cant change their order.
so for example I cant say the the default mode be natural size if I also selected the option above (fit to window)

another even better way would be to give the user the choice to out modes in the order he wants.
so that it works even with remember last mode .

**Comment by sblask** [comment]
I don't really have time to work on this. I see how it could be useful, but I don't use the extension that way.
